---
apiVersion: networking.tkg.tanzu.vmware.com/v1alpha1
kind: AKODeploymentConfig
metadata:
    name: install-ako-for-all
spec:
    cloudName: Default-Cloud
    serviceEngineGroup: Default-Group
    controller: 10.0.0.1
    adminCredentialRef:
        name: controller-credentials
        namespace: default
    certificateAuthorityRef:
        name: controller-ca
        namespace: default
    dataNetwork:
        name: VM Network
        cidr: 10.0.0.0/20
    controlPlaneNetwork:
        name: VM Network 2
        cidr: 10.1.0.0/20
    extraConfigs:
        disableStaticRouteSync: false
        ingress:
            disableIngressClass: true
            defaultIngressController: false

---
apiVersion: networking.tkg.tanzu.vmware.com/v1alpha1
kind: AKODeploymentConfig
metadata:
    name: install-ako-for-management-cluster
spec:
    clusterSelector:
        matchLabels:
            cluster-role.tkg.tanzu.vmware.com/management: ""
    cloudName: Default-Cloud
    serviceEngineGroup: MC-SEG
    controller: 10.0.0.1
    adminCredentialRef:
        name: controller-credentials
        namespace: default
    certificateAuthorityRef:
        name: controller-ca
        namespace: default
    dataNetwork:
        name: VM Network
        cidr: 10.0.0.0/20
    controlPlaneNetwork:
        name: VM Network 2
        cidr: 10.1.0.0/20
    extraConfigs:
        disableStaticRouteSync: false
        ingress:
            disableIngressClass: true
            defaultIngressController: false
